class Forecast {
    constructor(location, details) {
        this.location = location;
        this.currently = {
            summary: details.currently.summary,
            icon: details.currently.icon,
            precipIntensity: details.currently.precipIntensity,
            precipProbability: details.currently.precipProbability,
            temperature: details.currently.temperature,
            humidity: details.currently.humidity,
            pressure: details.currently.pressure,
            windSpeed: details.currently.windSpeed,
            windGust: details.currently.windGust,
            windBearing: details.currently.windBearing,
            cloudCover: details.currently.cloudCover,
            visibility: details.currently.visibility
        }
        this.hourly = {
            summary: details.hourly.summary,
            icon: details.hourly.icon,
            data: [
              {   time = details.hourly.data[0].time
                  summary: details.hourly.data[0].summary,
                      icon: details.hourly.data[0].icon,
                  precipIntensity: details.hourly.data[0].precipIntensity,
                  precipProbability: details.hourly.data[0].precipProbability,
                  temperature: details.hourly.data[0].temperature,
                  humidity: details.hourly.data[0].humidity,
                  pressure: details.hourly.data[0].pressure,
                  windSpeed: details.hourly.data[0].windSpeed,
                  windGust: details.hourly.data[0].windGust,
                  windBearing: details.hourly.data[0].windBearing,
                  cloudCover: details.hourly.data[0].cloudCover,
                  visibility: details.hourly.data[0].visibility
              }, {   time = details.hourly.data[1].time
                  summary: details.hourly.data[1].summary,
                      icon: details.hourly.data[1].icon,
                      precipIntensity: details.hourly.data[1].precipIntensity,
                      precipProbability: details.hourly.data[1].precipProbability,
                      temperature: details.hourly.data[1].temperature,
                      humidity: details.hourly.data[1].humidity,
                      pressure: details.hourly.data[1].pressure,
                      windSpeed: details.hourly.data[1].windSpeed,
                      windGust: details.hourly.data[1].windGust,
                      windBearing: details.hourly.data[1].windBearing,
                      cloudCover: details.hourly.data[1].cloudCover,
                      visibility: details.hourly.data[1].visibility
              }, {   time = details.hourly.data[2].time
                  summary: details.hourly.data[2].summary,
                      icon: details.hourly.data[2].icon,
                      precipIntensity: details.hourly.data[2].precipIntensity,
                      precipProbability: details.hourly.data[2].precipProbability,
                      temperature: details.hourly.data[2].temperature,
                      humidity: details.hourly.data[2].humidity,
                      pressure: details.hourly.data[2].pressure,
                      windSpeed: details.hourly.data[2].windSpeed,
                      windGust: details.hourly.data[2].windGust,
                      windBearing: details.hourly.data[2].windBearing,
                      cloudCover: details.hourly.data[2].cloudCover,
                      visibility: details.hourly.data[2].visibility
              }, {   time = details.hourly.data[3].time
                  summary: details.hourly.data[3].summary,
                      icon: details.hourly.data[3].icon,
                      precipIntensity: details.hourly.data[3].precipIntensity,
                      precipProbability: details.hourly.data[3].precipProbability,
                      temperature: details.hourly.data[3].temperature,
                      humidity: details.hourly.data[3].humidity,
                      pressure: details.hourly.data[3].pressure,
                      windSpeed: details.hourly.data[3].windSpeed,
                      windGust: details.hourly.data[3].windGust,
                      windBearing: details.hourly.data[3].windBearing,
                      cloudCover: details.hourly.data[3].cloudCover,
                      visibility: details.hourly.data[3].visibility
              }, {   time = details.hourly.data[4].time
                  summary: details.hourly.data[4].summary,
                      icon: details.hourly.data[4].icon,
                      precipIntensity: details.hourly.data[4].precipIntensity,
                      precipProbability: details.hourly.data[4].precipProbability,
                      temperature: details.hourly.data[4].temperature,
                      humidity: details.hourly.data[4].humidity,
                      pressure: details.hourly.data[4].pressure,
                      windSpeed: details.hourly.data[4].windSpeed,
                      windGust: details.hourly.data[4].windGust,
                      windBearing: details.hourly.data[4].windBearing,
                      cloudCover: details.hourly.data[4].cloudCover,
                      visibility: details.hourly.data[4].visibility
              }, {   time = details.hourly.data[5].time
                  summary: details.hourly.data[5].summary,
                      icon: details.hourly.data[5].icon,
                      precipIntensity: details.hourly.data[5].precipIntensity,
                      precipProbability: details.hourly.data[5].precipProbability,
                      temperature: details.hourly.data[5].temperature,
                      humidity: details.hourly.data[5].humidity,
                      pressure: details.hourly.data[5].pressure,
                      windSpeed: details.hourly.data[5].windSpeed,
                      windGust: details.hourly.data[5].windGust,
                      windBearing: details.hourly.data[5].windBearing,
                      cloudCover: details.hourly.data[5].cloudCover,
                      visibility: details.hourly.data[5].visibility
              }, {   time = details.hourly.data[6].time
                  summary: details.hourly.data[6].summary,
                      icon: details.hourly.data[6].icon,
                      precipIntensity: details.hourly.data[6].precipIntensity,
                      precipProbability: details.hourly.data[6].precipProbability,
                      temperature: details.hourly.data[6].temperature,
                      humidity: details.hourly.data[6].humidity,
                      pressure: details.hourly.data[6].pressure,
                      windSpeed: details.hourly.data[6].windSpeed,
                      windGust: details.hourly.data[6].windGust,
                      windBearing: details.hourly.data[6].windBearing,
                      cloudCover: details.hourly.data[6].cloudCover,
                      visibility: details.hourly.data[6].visibility
              }, {   time = details.hourly.data[7].time
                  summary: details.hourly.data[7].summary,
                      icon: details.hourly.data[7].icon,
                      precipIntensity: details.hourly.data[7].precipIntensity,
                      precipProbability: details.hourly.data[7].precipProbability,
                      temperature: details.hourly.data[7].temperature,
                      humidity: details.hourly.data[7].humidity,
                      pressure: details.hourly.data[7].pressure,
                      windSpeed: details.hourly.data[7].windSpeed,
                      windGust: details.hourly.data[7].windGust,
                      windBearing: details.hourly.data[7].windBearing,
                      cloudCover: details.hourly.data[7].cloudCover,
                      visibility: details.hourly.data[7].visibility
              }
            ]
        },
        this.daily = {
          summary = details.daily.summary,
          icon = details.daily.icon,
          data = [{
            time: details.daily.data[0].time,
            summary: details.daily.data[0].summary,
            icon: details.daily.data[0].icon,
            sunriseTime: details.daily.data[0].sunriseTime,
            sunsetTime: details.daily.data[0].sunsetTime,
            precipIntensity: details.daily.data[0].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[0].precipIntensityMaxTime,
            precipProbability: details.daily.data[0].precipProbability,
            precipType: details.daily.data[0].precipType,
            temperatureHigh: details.daily.data[0].temperatureHigh,
            temperatureLow: details.daily.data[0].temperatureLow,
            humidity: details.daily.data[0].humidity,
            pressure: details.daily.data[0].pressure,
            windSpeed: details.daily.data[0].windSpeed,
            windGust: details.daily.data[0].windGust,
            cloudCover: details.daily.data[0].cloudCover,
            visibility: details.daily.data[0].visibility,
            temperatureMin: details.daily.data[0].temperatureMin,
            temperatureMax: details.daily.data[0].temperatureMax
          }, {
            time: details.daily.data[1].time,
            summary: details.daily.data[1].summary,
            icon: details.daily.data[1].icon,
            sunriseTime: details.daily.data[1].sunriseTime,
            sunsetTime: details.daily.data[1].sunsetTime,
            precipIntensity: details.daily.data[1].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[1].precipIntensityMaxTime,
            precipProbability: details.daily.data[1].precipProbability,
            precipType: details.daily.data[1].precipType,
            temperatureHigh: details.daily.data[1].temperatureHigh,
            temperatureLow: details.daily.data[1].temperatureLow,
            humidity: details.daily.data[1].humidity,
            pressure: details.daily.data[1].pressure,
            windSpeed: details.daily.data[1].windSpeed,
            windGust: details.daily.data[1].windGust,
            cloudCover: details.daily.data[1].cloudCover,
            visibility: details.daily.data[1].visibility,
            temperatureMin: details.daily.data[1].temperatureMin,
            temperatureMax: details.daily.data[1].temperatureMax
          }, {
            time: details.daily.data[2].time,
            summary: details.daily.data[2].summary,
            icon: details.daily.data[2].icon,
            sunriseTime: details.daily.data[2].sunriseTime,
            sunsetTime: details.daily.data[2].sunsetTime,
            precipIntensity: details.daily.data[2].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[2].precipIntensityMaxTime,
            precipProbability: details.daily.data[2].precipProbability,
            precipType: details.daily.data[2].precipType,
            temperatureHigh: details.daily.data[2].temperatureHigh,
            temperatureLow: details.daily.data[2].temperatureLow,
            humidity: details.daily.data[2].humidity,
            pressure: details.daily.data[2].pressure,
            windSpeed: details.daily.data[2].windSpeed,
            windGust: details.daily.data[2].windGust,
            cloudCover: details.daily.data[2].cloudCover,
            visibility: details.daily.data[2].visibility,
            temperatureMin: details.daily.data[2].temperatureMin,
            temperatureMax: details.daily.data[2].temperatureMax
          }, {
            time: details.daily.data[3].time,
            summary: details.daily.data[3].summary,
            icon: details.daily.data[3].icon,
            sunriseTime: details.daily.data[3].sunriseTime,
            sunsetTime: details.daily.data[3].sunsetTime,
            precipIntensity: details.daily.data[3].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[3].precipIntensityMaxTime,
            precipProbability: details.daily.data[3].precipProbability,
            precipType: details.daily.data[3].precipType,
            temperatureHigh: details.daily.data[3].temperatureHigh,
            temperatureLow: details.daily.data[3].temperatureLow,
            humidity: details.daily.data[3].humidity,
            pressure: details.daily.data[3].pressure,
            windSpeed: details.daily.data[3].windSpeed,
            windGust: details.daily.data[3].windGust,
            cloudCover: details.daily.data[3].cloudCover,
            visibility: details.daily.data[3].visibility,
            temperatureMin: details.daily.data[3].temperatureMin,
            temperatureMax: details.daily.data[3].temperatureMax
          }, {
            time: details.daily.data[4].time,
            summary: details.daily.data[4].summary,
            icon: details.daily.data[4].icon,
            sunriseTime: details.daily.data[4].sunriseTime,
            sunsetTime: details.daily.data[4].sunsetTime,
            precipIntensity: details.daily.data[4].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[4].precipIntensityMaxTime,
            precipProbability: details.daily.data[4].precipProbability,
            precipType: details.daily.data[4].precipType,
            temperatureHigh: details.daily.data[4].temperatureHigh,
            temperatureLow: details.daily.data[4].temperatureLow,
            humidity: details.daily.data[4].humidity,
            pressure: details.daily.data[4].pressure,
            windSpeed: details.daily.data[4].windSpeed,
            windGust: details.daily.data[4].windGust,
            cloudCover: details.daily.data[4].cloudCover,
            visibility: details.daily.data[4].visibility,
            temperatureMin: details.daily.data[4].temperatureMin,
            temperatureMax: details.daily.data[4].temperatureMax
          }, {
            time: details.daily.data[5].time,
            summary: details.daily.data[5].summary,
            icon: details.daily.data[5].icon,
            sunriseTime: details.daily.data[5].sunriseTime,
            sunsetTime: details.daily.data[5].sunsetTime,
            precipIntensity: details.daily.data[5].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[5].precipIntensityMaxTime,
            precipProbability: details.daily.data[5].precipProbability,
            precipType: details.daily.data[5].precipType,
            temperatureHigh: details.daily.data[5].temperatureHigh,
            temperatureLow: details.daily.data[5].temperatureLow,
            humidity: details.daily.data[5].humidity,
            pressure: details.daily.data[5].pressure,
            windSpeed: details.daily.data[5].windSpeed,
            windGust: details.daily.data[5].windGust,
            cloudCover: details.daily.data[5].cloudCover,
            visibility: details.daily.data[5].visibility,
            temperatureMin: details.daily.data[5].temperatureMin,
            temperatureMax: details.daily.data[5].temperatureMax
          }, {
            time: details.daily.data[6].time,
            summary: details.daily.data[6].summary,
            icon: details.daily.data[6].icon,
            sunriseTime: details.daily.data[6].sunriseTime,
            sunsetTime: details.daily.data[6].sunsetTime,
            precipIntensity: details.daily.data[6].precipIntensity,
            precipIntensityMax:precipIntensityMax,
            precipIntensityMaxTime: details.daily.data[6].precipIntensityMaxTime,
            precipProbability: details.daily.data[6].precipProbability,
            precipType: details.daily.data[6].precipType,
            temperatureHigh: details.daily.data[6].temperatureHigh,
            temperatureLow: details.daily.data[6].temperatureLow,
            humidity: details.daily.data[6].humidity,
            pressure: details.daily.data[6].pressure,
            windSpeed: details.daily.data[6].windSpeed,
            windGust: details.daily.data[6].windGust,
            cloudCover: details.daily.data[6].cloudCover,
            visibility: details.daily.data[6].visibility,
            temperatureMin: details.daily.data[6].temperatureMin,
            temperatureMax: details.daily.data[6].temperatureMax
          }
        ]
      }
        }
    }
}

module.exports = Forecast;
